### PR TITLE
Update to use env variable to get Github token if JSON file doesn't exist

### PR DESCRIPTION
**Pull request by mauris**
Instead of using a file, the token can now be loaded from an environment variable. I've updated README and also took the liberty to update dependencies.

Usage example:

    $ GITHUB_TOKEN=<token-goes-here> thank-you-stars

See also: #4

### CODE REVIEW

**Comment by teppeis** [comment]
@mauris don't remove loading from JSON! Just add loading from env var.
Priority of loading config:

1. JSON (existing)
2. env variables (new!)

**Comment by mauris** [comment]
okies! I will reverse my changes on that! Is there any particular order? (file first then env var or env var first then file?)

**Comment by teppeis** [comment]
@mauris thanks! "file first then env var" is better.

**Comment by mauris** [comment]
ICYMI @teppeis I've made a push to this PR.

**Comment by teppeis** [comment]
@mauris merged and published as v1.1.0! thanks!

**Pull request merged**
